server:
  port: 8080

spring:
  application:
    name: search-engine
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sasha
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.memdb.service.kafka.CustomSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.memdb.service.kafka.CustomDeserializer
    listener:
      missing-topics-fatal: false

logging:
  level:
    root: INFO

minio:
  endpoint: http://localhost:9000
  accessKey: 123123
  secretKey: 123123123
  bucketName: mem-images

elasticsearch:
  url: localhost:9200
