server:
  port: 8080

spring:
  application:
    name: search-engine
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sasha
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: INFO

minio:
  endpoint: http://localhost:9000
  accessKey: minioaccesskey
  secretKey: miniosecretkey
  bucketName: mem-images

