openapi: 3.0.0
info:
  title: Image Controller API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

tags:
  - name: image
    description: Operations with images

paths:
  /image:
    post:
      tags:
        - image
      summary: Upload an image
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                type: string
    get:
      tags:
        - image
      summary: Get an image by ID
      parameters:
        - in: path
          name: imageId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Image retrieved successfully
          content:
            image/jpeg:
              schema:
                type: string
        '404':
          description: Image not foundolean