services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  elasticsearch:
    image: elasticsearch:8.13.0

    ports:
      - 9200:9200
      - 9300:9300

    mem_limit: 1512MB

    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ELASTIC_PASSWORD: 123qwe
      KIBANA_PASSWORD: 789zxc
      CLUSTER_NAME: memedb-text-search


  kibana:
    image: kibana:8.13.0
    ports:
      - 5601:5601


  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: boss
      MINIO_ROOT_PASSWORD: bigboss228


  telegram-bot:
    restart: always
    build:
      context: tg-bot
    volumes:
      - ./etc/tg-bot:/etc/memDB/telegram

  search-engine:
    restart: always
    build:
      context: search-engine
    volumes:
      - ./etc/tg-bot:/etc/memDB/search-engine/

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
