server:
  port: ${port:8090}

spring:
  application:
    name: memedbbot
  data:
    mongodb:
      uri: mongodb://localhost:27017/${bot.mongoCollection}
      auto-index-creation: true

bot:
  telegramToken:
  mongoCollection: memeDBBot

search-engine:
  url: http://localhost:8080

logging:
  file:
    name: ${log.dir:/tmp}/memedbbot.main.log
