server:
  port: ${port:8090}

spring:
  application:
    name: memedbbot
  data:
    mongodb:
      uri: mongodb://mongo/${bot.mongoCollection}
      auto-index-creation: true
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: service.kafka.CustomDeserializer
    listener:
      missing-topics-fatal: false

bot:
  telegramToken:
  mongoCollection: memeDBBot

search-engine:
  url: http://localhost:8080

logging:
  file:
    name: ${log.dir:/tmp}/memedbbot.main.log
